; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.26"

; Profiles
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[os2web][download][type] = ""
projects[os2web][download][url] = ""
projects[os2web][type] = "profile"

; Modules
projects[views_bulk_operations][version] = "3.2"

projects[admin_menu][version] = "3.0-rc4"

projects[service_links][version] = "2.2"

projects[better_formats][version] = "1.0-beta1+2-dev"

projects[bigmenu][version] = "1.2"

projects[ctools][version] = "1.3"

projects[ckeditor][version] = "1.13"

projects[content_taxonomy][version] = "1.0-beta2"

projects[crumbs][version] = "2.0-beta13"

projects[date][version] = "2.7"

projects[delta][version] = "3.0-beta11"

projects[devel][version] = "1.4"

projects[eim][version] = "1.3"

projects[elements][version] = "1.4"

projects[entity][version] = "1.3"

projects[eu-cookie-compliance][version] = "1.12"

projects[features][version] = "2.0"

projects[feeds][version] = "2.0-alpha8"

projects[feeds_xpathparser][version] = "1.0-beta4+2-dev"

projects[field_collection][version] = "1.0-beta5"

projects[field_collection_views][version] = "1.0-beta3"

projects[field_formatter_settings][version] = "1.1"

projects[field_group][version] = "1.3"

projects[field_slideshow][version] = "1.82"

projects[fieldable_panels_panes][version] = "1.5"

projects[file_entity][version] = "2.0-alpha3"

projects[filefield_sources][version] = "1.9"

projects[honeypot][version] = "1.16"

projects[icon][version] = "1.0-beta3"

projects[imagefield_crop][version] = "1.1"
projects[imagefield_crop][patches][] = "http://drupal.org/files/imagefield_crop-undefined_index_und-1913412-9.patch"

projects[imagefield_focus][version] = "1.0"

projects[jcarousel][version] = "2.6"

projects[job_scheduler][version] = "2.0-alpha3"

projects[jquery_update][version] = "2.3"

projects[l10n_update][version] = "1.0-beta3"

projects[libraries][version] = "2.2"

projects[lightbox2][version] = "1.0-beta1+9-dev"

projects[link][version] = "1.2"

projects[linked_field][version] = "1.9"

projects[linkit][version] = "3.1"

projects[mailchimp][version] = "2.12"

projects[media][version] = "2.0-alpha3"

projects[menu_block][version] = "2.3"

projects[menu_minipanels][version] = "1.1"

projects[menu_position][version] = "1.1"

projects[metatag][version] = "1.0-beta9"

projects[module_filter][version] = "2.0-alpha2"

projects[multiform][version] = "1.0"

projects[references][version] = "2.1"

projects[options_element][version] = "1.10"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[os2web_base][download][type] = ""
projects[os2web_base][download][url] = ""
projects[os2web_base][type] = "module"
projects[os2web_base][version] = "1.0-beta1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[os2web_base_panels][download][type] = ""
projects[os2web_base_panels][download][url] = ""
projects[os2web_base_panels][type] = "module"
projects[os2web_base_panels][version] = "1.0-beta1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[os2web_borger_dk][download][type] = ""
projects[os2web_borger_dk][download][url] = ""
projects[os2web_borger_dk][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[os2web_esdh_field][download][type] = ""
projects[os2web_esdh_field][download][url] = ""
projects[os2web_esdh_field][type] = "module"
projects[os2web_esdh_field][version] = "1.0-beta1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[os2web_taxon_api][download][type] = ""
projects[os2web_taxon_api][download][url] = ""
projects[os2web_taxon_api][type] = "module"
projects[os2web_taxon_api][version] = "1.0-beta1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[os2web_taxon_taxonomy][download][type] = ""
projects[os2web_taxon_taxonomy][download][url] = ""
projects[os2web_taxon_taxonomy][type] = "module"
projects[os2web_taxon_taxonomy][version] = "1.1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[os2web_taxonomies][download][type] = ""
projects[os2web_taxonomies][download][url] = ""
projects[os2web_taxonomies][type] = "module"
projects[os2web_taxonomies][version] = "1.0-beta1"

projects[panels][version] = "3.3"

projects[pathauto][version] = "1.2"

projects[plupload][version] = "1.6"

projects[print][version] = "1.2"

projects[respondjs][version] = "1.2"

projects[simplehtmldom][version] = "1.12"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[spotbokse2][download][type] = ""
projects[spotbokse2][download][url] = ""
projects[spotbokse2][type] = "module"
projects[spotbokse2][subdir] = "os2web"
projects[spotbokse2][version] = "1.0"

projects[strongarm][version] = "2.0"

projects[superfish][version] = "1.8"

projects[taxonomy_manager][version] = "1.0"

projects[token][version] = "1.5"

projects[transliteration][version] = "3.1"

projects[views][version] = "3.7"

projects[views_bootstrap][version] = "3.0"

projects[views_php][version] = "1.x-dev"

projects[views_rss][version] = "2.0-rc3"

projects[views_slideshow][version] = "3.0"

projects[views_tree][version] = "2.0"

projects[webform][version] = "3.19"

projects[workbench][version] = "1.2"

projects[workbench_moderation][version] = "1.3"

; Themes
projects[best_responsive][version] = "1.1"

projects[bootstrap][version] = "3.0"

projects[ember][version] = "2.0-alpha2"

projects[wetkit_ember][version] = "1.3"

; Modules
projects[os2web-deploy][type] = "module"
projects[os2web-deploy][download][type] = "git"
projects[os2web-deploy][download][url] = "git@github.com:OS2web/os2web-deploy.git"
projects[os2web-deploy][download][branch] = "feature/recursive-make"
projects[os2web-deploy][download][revision] = "d2022b9d3d482d09dafd01e1a0ecb1ec409b954c"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[fatal: Not a git repository (or any parent up to mount point ][download][type] = ""
projects[fatal: Not a git repository (or any parent up to mount point ][download][url] = ""
projects[fatal: Not a git repository (or any parent up to mount point ][type] = "theme"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[SolrPhpClient][download][type] = ""
libraries[SolrPhpClient][download][url] = ""
libraries[SolrPhpClient][directory_name] = "SolrPhpClient"
libraries[SolrPhpClient][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.jcarousel][download][type] = ""
libraries[jquery.jcarousel][download][url] = ""
libraries[jquery.jcarousel][directory_name] = "jquery.jcarousel"
libraries[jquery.jcarousel][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[tinymce][download][type] = ""
libraries[tinymce][download][url] = ""
libraries[tinymce][directory_name] = "tinymce"
libraries[tinymce][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = ""
libraries[ckeditor][download][url] = ""
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[superfish][download][type] = ""
libraries[superfish][download][url] = ""
libraries[superfish][directory_name] = "superfish"
libraries[superfish][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[simplepie][download][type] = ""
libraries[simplepie][download][url] = ""
libraries[simplepie][directory_name] = "simplepie"
libraries[simplepie][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[htmlpurifier][download][type] = ""
libraries[htmlpurifier][download][url] = ""
libraries[htmlpurifier][directory_name] = "htmlpurifier"
libraries[htmlpurifier][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.cycle][download][type] = ""
libraries[jquery.cycle][download][url] = ""
libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.imagesloaded][download][type] = ""
libraries[jquery.imagesloaded][download][url] = ""
libraries[jquery.imagesloaded][directory_name] = "jquery.imagesloaded"
libraries[jquery.imagesloaded][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[plupload][download][type] = ""
libraries[plupload][download][url] = ""
libraries[plupload][directory_name] = "plupload"
libraries[plupload][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[qtip][download][type] = ""
libraries[qtip][download][url] = ""
libraries[qtip][directory_name] = "qtip"
libraries[qtip][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[backbone][download][type] = ""
libraries[backbone][download][url] = ""
libraries[backbone][directory_name] = "backbone"
libraries[backbone][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[mailchimp][download][type] = ""
libraries[mailchimp][download][url] = ""
libraries[mailchimp][directory_name] = "mailchimp"
libraries[mailchimp][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[respondjs][download][type] = ""
libraries[respondjs][download][url] = ""
libraries[respondjs][directory_name] = "respondjs"
libraries[respondjs][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[underscore][download][type] = ""
libraries[underscore][download][url] = ""
libraries[underscore][directory_name] = "underscore"
libraries[underscore][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[modernizr][download][type] = ""
libraries[modernizr][download][url] = ""
libraries[modernizr][directory_name] = "modernizr"
libraries[modernizr][type] = "library"

